### ISSUE TITLE
update elasticsearch container to 7.x

### ISSUE THREAD

**Issue by monotek** [zammad/zammad-docker-compose#109]
* update elasticsearch container to 7.x
* add upgrade note

**Comment by kevingiesuebel** [comment]
+1
Update notes would be very great. Only change the Version in the .env config did not work...
What are the steps to upgrade/update zammad over docker / docker-compose.yml

**Comment by monotek** [comment]
not sure. we'll have to see if an update is even possible or if we have to drop & recreate all data.

see also: https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html

**Comment by Berdir** [comment]
Maybe that could also switch to the OSS version then (see https://github.com/elastic/elasticsearch-docker/issues/36) Instead of removing x-pack manually?

Somehow it was still enabled for me and I've only just noticed now that there was a 30GB container logfile because it was constantly complaining about an expired license..
