### ISSUE TITLE
Rebuild search index during upgrade to 3.2

### ISSUE THREAD

**Issue by t3easy** [zammad/zammad-docker-compose#121]
### Infos:

* Docker version: 19.03
* Docker-compose version: docker-compose version 1.25.1-rc1
* Operating system (Docker host): Ubunto

### Expected behavior:

* Rebuild search index during upgrade to 3.2 because layout has changed https://community.zammad.org/t/zammad-3-2-is-available/3656

### Actual behavior:

* The index isn't rebuild
See https://github.com/zammad/zammad/issues/2858

### Steps to reproduce the behavior:

* Upgrade a 3.x to 3.2

**Comment by MrGeneration** [comment]
Did you run `rake searchindex:rebuid` manually like I requested you to do so? :)
The above command has to be run within the `zammad-railsserver` container.

**Comment by t3easy** [comment]
Yes, I executed `docker-compose exec zammad-railsserver bundle exec rake searchindex:rebuild`

**Comment by MrGeneration** [comment]
The issue persists? Any erorr messages that could help further?

**Comment by t3easy** [comment]
After rebulding the index the user search in the ticket is fine.

**Comment by MrGeneration** [comment]
@monotek is there a way to trigger this rebuild once when it's needed or do we need to clarify it better in our announcements?

**Comment by monotek** [comment]
Not sure. 

I guess we could only rebuild automatically on every / restart update which would be time consuming.

If there would be a es query one could use to see if an upgrade is required we could automate it.

**Comment by MrGeneration** [comment]
Thanks for your feedback, personally I'd like to keep the function of the container as it is.
I really don't like the idea to reindex the whole container on every restart.

Especially when you have some issues and fiddle around this might be in your way. I mean it works well for 10 tickets, but as soon as you have 100,000 tickets, this will be a pain, because this steps usually takes 30-120 minutes depending on your machines.

@thorsteneckel what do you think?
I kinda like the approach to "recognize a reindex is needed". 
If this is a thing, this should be some UI popup that will keep reminding the administrator to reindex his container.

This will catch admins that didn't read the release notes or community (so they basically have no chance in knowing it). 

I'm not too sure about automatic reindexing, because in "bad" situations you could trigger a reindex in a situation that doesn't fit.

**Comment by thorsteneckel** [comment]
We can create an enhancement issue over at https://github.com/zammad/zammad to have this flag. However, the priority is low. It's a UX worthy improvement but having an entry in the release notes was sufficient for the majority so far.
