### ISSUE TITLE
Custom notification is erased after reboot

### ISSUE THREAD

**Issue by ricardolimaui** [zammad/zammad-docker-compose#169]
### Infos:

* Docker version: 19.03.8
* Docker-compose version: 1.17.1
* Operating system (Docker host): Ubuntu 18.04.4 LTS

### Expected behavior:

* the changes remain active after the reboot

### Actual behavior:

* all the files are replaced with the original ones, which makes me lost all the changes

### Steps to reproduce the behavior:

*Customise the notification as it is explain in here https://admin-docs.zammad.org/en/latest/manage/trigger/system-notifications.html#how-can-i-customize-them

**Comment by MrGeneration** [comment]
Sorry but this is due to how docker containers work.
You'd have to manually patch them and have your own container versions.

This is not a bug, but a functionality thing of docker.
If you need to modify whatever part of Zammad that doesn't live in the database, you'll have to use package or source code installations.

**Comment by monotek** [comment]
True. Best practice would be to rebuild the container with your changes.

**Comment by ricardolimaui** [comment]
Thanks for the advice. I also tried to disable the container Zammad init and now my changes still persist even after reboot. But probably is not recommended, because that container should be needed... and not only for init
