### ISSUE TITLE
Authenticated SMTP choice

### ISSUE THREAD

**Issue by filippolmt** [zammad/zammad-docker-compose#210]
Hi, I have a problem, I have configured the office 365 shard box and I am able to receive emails without problems, but now, since it does not have a license, I cannot send emails. Can I send emails using an authenticated smtp instead of using the office account?

**Comment by MrGeneration** [comment]
@monotek if you're not okay with me fishing out not docker related topics please let me know, I'll also stop that.

Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
