### ISSUE TITLE
psql: FATAL:  role "postgres" does not exist

### ISSUE THREAD

**Issue by theoneandonly-vector** [zammad/zammad-docker-compose#233]
I use the Univention Appcenter Version and I want to restore a backup (did this before successfully)

but as soon as I want to create the db I get:
psql: FATAL:  role "postgres" does not exist
or
psql: FATAL:  role "root" does not exist

so what can I do to get a working postgres user.. so I can restore my DB?

**Comment by theoneandonly-vector** [comment]
the error happens inside this docker:
```
docker exec -it zammad_zammad-postgresql_1 /bin/sh
```

**Comment by theoneandonly-vector** [comment]
that's not a question.. this is not fixable from user-side.. or how can you create arole when there is no role (root/zammad/psotgres do not exist as postgresql roles.. so there's no way to create a user)?

**Comment by MrGeneration** [comment]
> that's not a question.

Yes it is.
You did that before, sure, but probably on a version **older** than 3.6 and simply don't understand the changes that came with that version.

Please head over to the community board where UCS Users without support should go.
No offense, really - it's not an issue with the compose.

> I use the Univention Appcenter Version and I want to restore a backup (did this before successfully)

You didn't even care to provide the used App version.
Doesn't matter through because it doesn't belong here.
