### ISSUE TITLE
Zammad scalability on k8s

### ISSUE THREAD

**Issue by mrad-bilel** [zammad/zammad-docker-compose#246]
# Infos

* helm chart version: zammad-3.1.0
* Application version: 3.6.0
* kubernetes version: v1.16

# Expected behavior

Be able to scale zammad statefulsets 

```
kk
NAME                                 READY   STATUS    RESTARTS   AGE 
zammad-master-0                      1/1     Running   0          16h
zammad-0                             4/4     Running   0          16h
zammad-memcached-cdb9865f-s9dcz      1/1     Running   0          16h
```

# Actual behavior

No way to scale zammad using helm chart values , how  to make zammad highly available and fault tolerant ?

**Comment by mrad-bilel** [comment]
Any update please

**Comment by Nitair** [comment]
Dear @mrad-bilel ,

is there any specific reason to put the zammad application into a statefulset (instead only the database)?

**Comment by MrGeneration** [comment]
The helm repository lives here:
https://github.com/zammad/zammad-helm

**Comment by mrad-bilel** [comment]
@MrGeneration  , it does not answer my question, i'm planning to perform the migration soon , I'm asking why we cannot scale zammad pod that has 4 containers (railserver,nginx,scheduler,websocket) ?

**Comment by MrGeneration** [comment]
You're asking technical questions in our repos.
I am not answering those here. The main maintainer of this repo does accept questions here which is why I'm ignoring most of the stuff here.

Your question affects a very old version that, at that state, didn't have such options at all.
Zammad 5.x did come with better support for scaling.

That's as far as I can and will help - sorry.
