### ISSUE TITLE
Remove docker-compose.override.yml form repo

### ISSUE THREAD

**Issue by devNan0** [zammad/zammad-docker-compose#251]
The docker-compose.override.yml should be removed from this repo and added to .gitignore.

Otherwise its not possible to actually change thins in the override file because it will be overwritten.

**Comment by t3easy** [comment]
I moved the ports to `docker-compose.override.yml` because in scenarios with a revers proxy, you would have to remove the port ssettings from the docker-compose.yml as it is not possible to remove a port by another override.
Use `-f` on cli or use `COMPOSE_FILE` in your `.env` (https://docs.docker.com/compose/reference/envvars/#compose_file) to declare the files you want to load.
