### ISSUE TITLE
what editor and passwd for rot (container)""I edited /opt/zammad/lib/telegram.rb"" how edit?

### ISSUE THREAD

**Issue by errooorr** [zammad/zammad-docker-compose#297]
[Telegram Channel Error: The webhook could not be saved by Telegram, seems to be an invalid URL](https://community.zammad.org/t/telegram-channel-error-the-webhook-could-not-be-saved-by-telegram-seems-to-be-an-invalid-url/9598)

**Comment by MrGeneration** [comment]
Sorry, but this seems to be a technical question.
Please note that this repository is the wrong place for technical questions.
Instead, please refer the Zammad community over at: https://community.zammad.org .

In case this turns out the be a bug and no technical question, we'll transfer the relevant information to this repo!

If you require commercial grade support and are no hosted or support contract customer, you can check out our support contracts here: https://zammad.com/pricing#selfhosted
*If you're paying customer already, please consult your Zammad support for assistance! :-)*
