### ISSUE TITLE
Shared folder /var should be added for Zammad 6.0

### ISSUE THREAD

**Issue by mgruner** [zammad/zammad-docker-compose#350]
# Infos

* Docker version: 24.0.2
* Docker-compose version: 2.18.1
* Operating system (Docker host): MacOS

# Expected behavior

* There should be a volume for the new folder `var` for data that needs to be shared in the cluster as described in the [README.md](https://github.com/zammad/zammad/blob/develop/var/README.md)

# Actual behavior

* There is a shared folder for the whole of `/opt/zammad` which will probably be changed/removed now that rsync is no longer used.

**Comment by monotek** [comment]
i've already tried but run into some problems.
need more time to test.
unfotunately i'm very busy at the moment.

**Comment by HEP85** [comment]
**+1** on this one

I recently tried to migrate my installation to Docker and having the whole /opt/zammad shared/persistent was a non-starter, because I wondered what happens if I pull a new image, but all the old files are persisted in /opt/zammad. I could probably not even update.

Really looking forward to this change :-)

**Comment by monotek** [comment]
Before 6.0 some rsync magic in the mounted volume was used during update.
This was needed for historical reasons, as at some point some files has been stored in the fielsystem.

**Comment by monotek** [comment]
Will be fixed inside: https://github.com/zammad/zammad-docker-compose/pull/347
