### ISSUE TITLE
Websocket failed with rancher and rancher lb

### ISSUE THREAD

**Issue by cedvan** [zammad/zammad-docker-compose#40]
### Infos:

* Docker version: 17.04
* Operating system (Docker host): Rancher OS
* Orchestrator: Rancher cattle
* Rancher version: 1.5.5
* Docker volume driver: rancher-nfs
* Rancher load balancer version : v0.6.4

### Expected behavior:

* Real time with chat

### Actual behavior:

* Chat enabled, but real time don't work, refresh page is necessary to display message...
* The websocket does not seem to work

### Steps to reproduce the behavior:

* Use rancher-composer.yml and docker-compose.yml to load stack on rancher with configure rancher-nfs as volume driver
* Create loadbalancer service to provide HTTPS traffic with valid certificate to zammad-nginx on port 80

#### Possible problem

- Load balancer don't support websocket ?
- HA Proxy has bad configuration to websocket ?

**Comment by thebennos** [comment]
same issue. 
HA Proxy to serve SSL 
Chat does not work. I get notifications that the new client is waiting after button Click, but the chat does not appear. No JS error message in the browser console. 

I checked the docker images logs and do not find a problem there, means no error.

**Comment by monotek** [comment]
Hope its fixed with updated rancher file: rancher/community-catalog#617

**Comment by niels-k** [comment]
I also had issues to get the chat working.
As i used docker-compose, but i changed the port from 80 to another one, 9336.
(Port 80 is already in use by apache)
I copied the chat.js into my local environment and i changed in the following part
```
    ZammadChat.prototype.detectHost = function() {
      var protocol;
      protocol = 'ws://';
      if (scriptProtocol === 'https') {
        protocol = 'wss://';
      }
      **return this.options.host = "" + protocol + scriptHost + "/ws";**
    };

```
the line 
`return this.options.host = "" + protocol + scriptHost + "/ws";`
into
` return this.options.host = "" + protocol + scriptHost + "**9936:**/ws";`
so
` return this.options.host = "" + protocol + scriptHost + "**<Your_Port>:**/ws";`

Then i used my local file to be included into the chat script instead of the one of the docker environment and that fixed the chat issue for me.
Hope it can help you out.

**Comment by monotek** [comment]
Does this problem still exist?

**Comment by monotek** [comment]
We have a new rancher version in the community catalog:

https://github.com/rancher/community-catalog/tree/master/templates/zammad/1

Closing for now as no feedback earlier.
