### ISSUE TITLE
Elasticsearch Container does not start

### ISSUE THREAD

**Issue by pit-c** [zammad/zammad-docker-compose#84]
### Infos:

* Docker version: 17.09.1-ce
* Docker-compose version: 1.21
* Operating system (Docker host): unRaid 6.5.3 Linux

### Expected behavior:
Elasticsearch up and running ;-)

### Actual behavior:

*I get the following message when using zammad-docker-compose. I think the issue is with elasticsearch. I does not start. Here is the log:

[INFO ][o.e.b.BootstrapChecks ] [384YkP0] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed

[1]: max file descriptors [40960] for elasticsearch process is too low, increase to at least [65536]

### Steps to reproduce the behavior:

* Starting up the elasticsearch docker container manually

**Comment by MrGeneration** [comment]
Hey,

actually you wrote what your problem is:
**[1]: max file descriptors [40960] for elasticsearch process is too low, increase to at least [65536**

Please use our community board ( https://community.zammad.org ) as github is only for bugs. This is also to keep noise low to those, who subscribed our repos. :)

**Comment by pit-c** [comment]
Thank you for your hint, but I did that already and it did not work.

**Comment by monotek** [comment]
See documentation for needed command:

https://docs.zammad.org/en/latest/install-elasticsearch.html
